export const countries = [
  { value: "North America", label: "North America" },
  { value: "South America", label: "South America" },
  { value: "Central America", label: "Central America" },
  { value: "Caribbean", label: "Caribbean" },
  { value: "Central & South Asia", label: "Central & South Asia" },
  { value: "Northeastern Asia", label: "Northeastern Asia" },
  { value: "Southeastern Asia", label: "Southeastern Asia" },
  { value: "Australia and Oceania", label: "Australia and Oceania" },
  { value: "Northern Europe", label: "Northern Europe" },
  { value: "Southern Europe", label: "Southern Europe" },
  { value: "Eastern Europe", label: "Eastern Europe" },
  { value: "Western Europe", label: "Western Europe" },
  { value: "Middle East", label: "Middle East" },
  { value: "Northern Africa", label: "Northern Africa" },
  { value: "Southern Africa", label: "Southern Africa" },
  { value: "Western Africa", label: "Western Africa" }
];

export const pronouns = [
  "she/her",
  "they/them",
  "he/they",
  "she/they",
  "they/she",
  "they/he",
  "ze/hir",
  "xe/xem",
  "ey/em",
  "it/its"
];

export const languagesByRegion = {
  Africa: ["Afrikaans", "Amharic", "Arabic", "Hausa", "Igbo", "Somali", "Swahili", "Xhosa", "Yoruba", "Zulu"],
  Asia: [
    "Arabic",
    "Bengali",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Hindi",
    "Japanese",
    "Korean",
    "Malay",
    "Punjabi",
    "Tamil",
    "Telugu",
    "Thai",
    "Urdu",
    "Vietnamese"
  ],
  Europe: [
    "Albanian",
    "Basque",
    "Bulgarian",
    "Catalan",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Finnish",
    "French",
    "Galician",
    "German",
    "Greek",
    "Hungarian",
    "Icelandic",
    "Italian",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Norwegian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Swedish",
    "Ukrainian",
    "Welsh"
  ],
  MiddleEast: ["Arabic", "Hebrew", "Kurdish (Kurmanji)", "Kurdish (Sorani)", "Persian", "Pashto"],
  Americas: ["English", "French", "Haitian Creole", "Portuguese", "Quechua", "Spanish"],
  Oceania: ["Hawaiian", "Maori", "Samoan"]
};

export const socialChannels = [
  { name: "Discord", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386812/Discord_oqxmeb.svg" },
  { name: "Facebook", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386814/Facebook_zxycob.svg" },
  { name: "Instagram", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386821/Instagram_qpdoa3.svg" },
  { name: "Github", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386821/Github_lxjdh4.svg" },
  { name: "Pinterest", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386799/Pinterest_airjrr.svg" },
  { name: "Reddit", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386800/Reddit_nluude.svg" },
  { name: "Youtube", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386803/Youtube_xedjut.svg" },
  { name: "Medium", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386800/Medium_h0ihag.svg" },
  { name: "LinkedIn", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386798/LinkedIn_mrnvct.svg" },
  { name: "Snapchat", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386801/Snapchat_liypyl.svg" },
  { name: "Telegram", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386802/Telegram_drwaq5.svg" },
  { name: "Twitter", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386803/Twitter_btmxyb.svg" },
  { name: "Steemit", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386802/Steemit_gg2zq5.svg" },
  { name: "Mastodon", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386799/Mastodon_yjbvc3.svg" },
  {
    name: "Lens Protocol",
    icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386798/LensProtocol_ghjkgn.svg"
  },
  { name: "Bluesky", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386807/Bluesky_ttvreb.svg" },
  { name: "DeSo", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386812/Deso_saqtup.svg" },
  { name: "Mirror", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386798/Mirror_hfnky1.svg" },
  { name: "Substack", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386802/Substack_mkcdys.svg" },
  { name: "Farcaster", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386819/Farcaster_ogg61n.svg" },
  { name: "Audius", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386806/Audius_m7dpsk.svg" },
  { name: "Tiktok", icon: "https://res.cloudinary.com/dv52zu7pu/image/upload/v1751386802/Tiktok_qpxsbc.svg" }
];
