export const countries = [
  { value: "North America", label: "North America" },
  { value: "South America", label: "South America" },
  { value: "Central America", label: "Central America" },
  { value: "Caribbean", label: "Caribbean" },
  { value: "Central & South Asia", label: "Central & South Asia" },
  { value: "Northeastern Asia", label: "Northeastern Asia" },
  { value: "Southeastern Asia", label: "Southeastern Asia" },
  { value: "Australia and Oceania", label: "Australia and Oceania" },
  { value: "Northern Europe", label: "Northern Europe" },
  { value: "Southern Europe", label: "Southern Europe" },
  { value: "Eastern Europe", label: "Eastern Europe" },
  { value: "Western Europe", label: "Western Europe" },
  { value: "Middle East", label: "Middle East" },
  { value: "Northern Africa", label: "Northern Africa" },
  { value: "Southern Africa", label: "Southern Africa" }
];

export const pronouns = [
  "he/him",
  "she/her",
  "they/them",
  "he/they",
  "she/they",
  "they/she",
  "they/he",
  "ze/hir",
  "xe/xem",
  "ey/em",
  "it/its"
];

export const languagesByRegion = {
  Africa: ["Afrikaans", "Amharic", "Arabic", "Hausa", "Igbo", "Somali", "Swahili", "Xhosa", "Yoruba", "Zulu"],
  Asia: [
    "Arabic",
    "Bengali",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Hindi",
    "Japanese",
    "Korean",
    "Malay",
    "Punjabi",
    "Tamil",
    "Telugu",
    "Thai",
    "Urdu",
    "Vietnamese"
  ],
  Europe: [
    "Albanian",
    "Basque",
    "Bulgarian",
    "Catalan",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Finnish",
    "French",
    "Galician",
    "German",
    "Greek",
    "Hungarian",
    "Icelandic",
    "Italian",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Norwegian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Swedish",
    "Ukrainian",
    "Welsh"
  ],
  MiddleEast: ["Arabic", "Hebrew", "Kurdish (Kurmanji)", "Kurdish (Sorani)", "Persian", "Pashto"],
  Americas: ["English", "French", "Haitian Creole", "Portuguese", "Quechua", "Spanish"],
  Oceania: ["Hawaiian", "Maori", "Samoan"]
};
